application: design-answer
version: 1
runtime: php
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /(.*\.(jpeg|jpg|png))
  mime_type: (image/jpg|image/png)
  static_files: \1
  upload: (.*\.(jpeg|jpg|png))

- url: /(.*\.(php|html))
  script: \1

- url: /.*
  script: main.html